# Generated by Django 4.0.4 on 2022-05-30 22:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Remedio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('ean', models.CharField(max_length=255)),
                ('marca', models.CharField(max_length=255)),
                ('quantidade', models.CharField(max_length=255)),
                ('principio_ativo', models.CharField(max_length=255)),
                ('dosagem', models.CharField(max_length=255)),
                ('descricao', models.TextField(max_length=255)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('foto', models.ImageField(blank=True, upload_to='fotos/%Y/%m')),
            ],
        ),
    ]
